title: The Cloud Captain

description: >-
  Practical Azure architecture, infrastructure, migration,
  networking and automation guidance.

url: "https://thecloudcaptain.github.io"
baseurl: ""

author: The Cloud Captain

markdown: kramdown

exclude:
  - README.md
